Document: zig
Title: Debian zig Manual
Author: <insert document author here>
Abstract: This manual describes what zig is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zig/zig.sgml.gz

Format: postscript
Files: /usr/share/doc/zig/zig.ps.gz

Format: text
Files: /usr/share/doc/zig/zig.text.gz

Format: HTML
Index: /usr/share/doc/zig/html/index.html
Files: /usr/share/doc/zig/html/*.html
